exclude:
  - node_modules
  - script
  
sass:
  style: :compressed

# theme: jekyll-theme-texture

gems:
  - jekyll-paginate
  - jekyll/tagging
  
title: "One-shot Parametirc Audio Production Style Transfer with Application to Frequency Equalization"
subtitle: Support Material 
