exclude:
  - node_modules
  - script
sass:
  style: :compressed

theme: jekyll-theme-primer
  
title: Demo page for "One-shot Parametirc Audio Production Style Transfer with Application to Frequency Equalization"
