exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer
  
title: ONE-SHOT PARAMETRIC AUDIO PRODUCTION STYLE TRANSFERWITH APPLICATION TO FREQUENCY EQUALIZATION
#description: Primer is a Jekyll theme for GitHub Pages
